#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 17 13:54:34 2018

@author: ingridmariewolneberg
"""

n=float(input("Hvilket tall er n? "))
p=1

if n%1==0:
    for x in range(1,int(n)+1):  #må ha range til n+1 fordi range er bare til ikke til og med
        p=p*x
    print(p)
else:
    print("Feilmelding")
    
    
    
